apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: fluffy-octo-telegram-grpc=ghcr.io/shipperizer/fluffy-octo-telegram-grpc-app,fluffy-octo-telegram-web=ghcr.io/shipperizer/fluffy-octo-telegram-web-app
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/repo-3642839773
    argocd-image-updater.argoproj.io/fluffy-octo-telegram-grpc.pull-secret: pullsecret:argocd/regcred-github
    argocd-image-updater.argoproj.io/fluffy-octo-telegram-grpc.kustomize.image-name: ghcr.io/shipperizer/fluffy-octo-telegram-grpc-app
    argocd-image-updater.argoproj.io/fluffy-octo-telegram-grpc.allow-tags: regexp:^v[0-9]+.[0-9]+.*
    argocd-image-updater.argoproj.io/fluffy-octo-telegram-web.pull-secret: pullsecret:argocd/regcred-github
    argocd-image-updater.argoproj.io/fluffy-octo-telegram-web.kustomize.image-name: ghcr.io/shipperizer/fluffy-octo-telegram-web-app
    argocd-image-updater.argoproj.io/fluffy-octo-telegram-web.allow-tags: regexp:^v[0-9]+.[0-9]+.*
  name: fluffy-octo-telegram
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/kustomize
    repoURL: git@github.com:shipperizer/fluffy-octo-telegram.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
