apiVersion: skaffold/v2beta14
kind: Config
build:
  artifacts:
  - image: ghcr.io/shipperizer/fluffy-octo-telegram-grpc-app
    sync:
      infer:
      - "cmd/grpc/main.go"
      - "go.mod"
      - "go.sum"
    custom:
      buildCommand: ./buildx.sh
      dependencies:
        dockerfile:
          path: Dockerfile
          buildArgs:
            app_name: grpc
  - image: ghcr.io/shipperizer/fluffy-octo-telegram-web-app
    sync:
      infer:
      - "cmd/web/main.go"
      - "go.mod"
      - "go.sum"
    custom:
      buildCommand: ./buildx.sh
      dependencies:
        dockerfile:
          path: Dockerfile
          buildArgs:
            app_name: web
  local:
    push: true

deploy:
  kubectl:
    manifests:
    - "argocd.yaml"
    - "deployments/kustomize/extServer.yaml" # check README.md
  kustomize:
    paths:
      - "deployments/kustomize"

profiles:
- name: kaniko
  build:
    artifacts:
    - image: ghcr.io/shipperizer/fluffy-octo-telegram-grpc-app
      kaniko:
        image: gcr.io/kaniko-project/executor:arm64
        initImage: docker.io/busybox:stable
        buildArgs:
          app_name: grpc
          TARGETOS: linux
          TARGETARCH: arm64
    - image: ghcr.io/shipperizer/fluffy-octo-telegram-web-app
      kaniko:
        image: gcr.io/kaniko-project/executor:arm64
        initImage: docker.io/busybox:stable
        buildArgs:
          app_name: web
          TARGETOS: linux
          TARGETARCH: arm64
    cluster:
      randomDockerConfigSecret: true
      dockerConfig:
        secretName: regcred-github-kaniko
