kustomize:
  images:
  - ghcr.io/shipperizer/fluffy-octo-telegram-grpc-app=ghcr.io/shipperizer/fluffy-octo-telegram-grpc-app:v2.0.5
  - ghcr.io/shipperizer/fluffy-octo-telegram-web-app=ghcr.io/shipperizer/fluffy-octo-telegram-web-app:v2.0.5
