kustomize:
  images:
  - ghcr.io/shipperizer/fluffy-octo-telegram-grpc-app:v1.0.2
  - ghcr.io/shipperizer/fluffy-octo-telegram-web-app=ghcr.io/shipperizer/fluffy-octo-telegram-web-app:v1.0.2-15-g5eb8f73
