---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluffy-octo-telegram-app-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluffy-octo-telegram-app-grpc
  template:
    metadata:
      labels:
        app: fluffy-octo-telegram-app-grpc
      annotations:
        prometheus.io/path: /api/v0/metrics
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - image: ghcr.io/shipperizer/fluffy-octo-telegram-app-grpc
        name: fluffy-octo-telegram-app-grpc
        envFrom:
          - configMapRef:
              name: fluffy-octo-telegram-app-grpc
        ports:
        - containerPort: 9000
          name: grpc
          protocol: TCP
        - containerPort: 8000
          name: metrics
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=0.0.0.0:9000
            - -tls
            - -tls-no-verify
            # - -tls-ca-cert=/tls/ca.crt
            # - -tls-client-cert=/tls/tls.crt
            # - -tls-client-key=/tls/tls.key
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=0.0.0.0:9000
            - -tls
            - -tls-no-verify
            # - -tls-ca-cert=/tls/ca.crt
            # - -tls-client-cert=/tls/tls.crt
            # - -tls-client-key=/tls/tls.key
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
        - name: jwk
          mountPath: /jwk
          readOnly: true
      imagePullSecrets:
      - name: regcred-github
      volumes:
      - name: tls
        secret:
          secretName: fluffy-octo-telegram-tls
      - name: jwk
        projected:
          sources:
          - secret:
              name: jwk-pub
          - secret:
              name: jwk-priv
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: fluffy-octo-telegram-app-web
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: fluffy-octo-telegram-app-web
    template:
      metadata:
        labels:
          app: fluffy-octo-telegram-app-web
        annotations:
          prometheus.io/path: /api/v0/metrics
          prometheus.io/scrape: "true"
          prometheus.io/port: "8000"
      spec:
        containers:
        - image: ghcr.io/shipperizer/fluffy-octo-telegram-app-web
          name: fluffy-octo-telegram-app-web
          envFrom:
            - configMapRef:
                name: fluffy-octo-telegram-app-web
          ports:
          - name: http
            containerPort: 8000
          readinessProbe:
            httpGet:
              path: "/api/v0/metrics"
              port: 8000
            initialDelaySeconds: 5
            failureThreshold: 10
            timeoutSeconds: 5
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: "/api/v0/metrics"
              port: 8000
            initialDelaySeconds: 5
            failureThreshold: 10
            timeoutSeconds: 5
            periodSeconds: 30
          volumeMounts:
          - name: jwk
            mountPath: /jwk
            readOnly: true
        imagePullSecrets:
        - name: regcred-github
        volumes:
        - name: jwk
          projected:
            sources:
            - secret:
                name: jwk-pub
            - secret:
                name: jwk-priv
