apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: fluffy-octo-telegram-web-app
spec:
  routes:
    - conditions:
      - prefix: /api/.well-known/jwks.json
      services:
      - name: fluffy-octo-telegram-web-app
        port: 80
