apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  repo: fluffy-octo-telegram-app
resources:
- selfSignedIssuer.yaml
- certificate.yaml
- deployment.yaml
- service.yaml
- configMap.yaml
# - httpProxy.yaml
# - rootProxy.yaml
# - extServer.yaml excluded due to errors with kustomize

images:
- name: ghcr.io/shipperizer/fluffy-octo-telegram-grpc-app
  newTag: v1.0.0
- name: ghcr.io/shipperizer/fluffy-octo-telegram-web-app
  newTag: v1.0.0
