apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  repo: fluffy-octo-telegram-app
  version: v2
resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- vservice.yaml
- rbac.yaml
# - selfSignedIssuer.yaml
# - certificate.yaml
# - httpProxy.yaml
# - rootProxy.yaml
# - extServer.yaml excluded due to errors with kustomize

images:
- name: ghcr.io/shipperizer/fluffy-octo-telegram-grpc-app
  newTag: v1.0.0
- name: ghcr.io/shipperizer/fluffy-octo-telegram-web-app
  newTag: v1.0.0
