apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluffy-octo-telegram-grpc-app
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluffy-octo-telegram-grpc-app
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluffy-octo-telegram-grpc-app
subjects:
- kind: ServiceAccount
  name: fluffy-octo-telegram-grpc-app
roleRef:
  kind: Role
  name: fluffy-octo-telegram-grpc-app
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluffy-octo-telegram-web-app
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluffy-octo-telegram-web-app
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get","watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluffy-octo-telegram-web-app
subjects:
- kind: ServiceAccount
  name: fluffy-octo-telegram-web-app
roleRef:
  kind: Role
  name: fluffy-octo-telegram-web-app
  apiGroup: rbac.authorization.k8s.io