apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
  name: fluffy-octo-telegram-grpc-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 9443
    protocol: TCP
    targetPort: grpc
  selector:
    app: fluffy-octo-telegram-grpc-app
  type: ClusterIP
