---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /api/v0/metrics
    prometheus.io/scrape: "true"
  name: fluffy-octo-telegram-app-grpc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 9443
    protocol: TCP
    targetPort: grpc
  selector:
    app: fluffy-octo-telegram-app-grpc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /api/v0/metrics
    prometheus.io/scrape: "true"
  name: fluffy-octo-telegram-app-web
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: fluffy-octo-telegram-app-web
  type: ClusterIP
