---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /api/v0/metrics
    prometheus.io/scrape: "true"
  name: fluffy-octo-telegram-grpc-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: metrics
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: grpc
  selector:
    app: fluffy-octo-telegram-grpc-app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /api/v0/metrics
    prometheus.io/scrape: "true"
  name: fluffy-octo-telegram-web-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: fluffy-octo-telegram-web-app
  type: ClusterIP
