apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fluffy-octo-telegram-app  
spec:
  hosts:
  - "api.shipperizer.org"
  gateways:
  - istio-system/gateway
  http:
  - match:
    - uri:
        prefix: /api/v0/metrics
    route:
    - destination:
        port:
          number: 80
        host: fluffy-octo-telegram-grpc-app
  - match:
    - uri:
        prefix: /api/.well-known/jwks.json
    route:
    - destination:
        port: 
          number: 80     
        host: fluffy-octo-telegram-web-app
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fluffy-octo-telegram-grpc-app
spec:
  host: fluffy-octo-telegram-grpc-app
  exportTo:
    - "."
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN        
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fluffy-octo-telegram-web-app
spec:
  host: fluffy-octo-telegram-web-app
  exportTo:
    - "."
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN        