apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fluffy-octo-telegram-web-app  
spec:
  hosts:
  - "api.shipperizer.org"
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: /api/v0/metrics
    route:
    - destination:
        port:
          number: 80
        host: fluffy-octo-telegram-web-app   
        