apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fluffy-octo-telegram-app-web  
spec:
  hosts:
  - "api.shipperizer.org"
  gateways:
  - istio-system/gateway
  http:
  - match:
    - uri:
        prefix: /api/.well-known/jwks.json
    route:
    - destination:
        port: 
          number: 80     
        host: fluffy-octo-telegram-web-app
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fluffy-octo-telegram-app-grpc
spec:
  hosts:
  - fluffy-octo-telegram-app-grpc.default.svc.cluster.local   
  - fluffy-octo-telegram-app-grpc.svc.cluster.local   
  - fluffy-octo-telegram-app-grpc.svc.local   
  - fluffy-octo-telegram-app-grpc   
  http:
    - name: fluffy-octo-telegram-app-grpc
      route:
      - destination:
          host: fluffy-octo-telegram-app-grpc
          port: 
            number: 9443
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fluffy-octo-telegram-grpc-app
spec:
  host: fluffy-octo-telegram-grpc-app
  exportTo:
    - "."
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN        
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: fluffy-octo-telegram-web-app
spec:
  host: fluffy-octo-telegram-web-app
  exportTo:
    - "."
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN        